# Generated by Django 4.2.13 on 2024-06-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacSearch', '0004_vacancy'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
