# Generated by Django 4.2.13 on 2024-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacSearch', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='title',
            new_name='vacancy_name',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_profile',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
