# Generated by Django 4.2.13 on 2024-06-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacSearch', '0006_rename_title_vacancy_vacancy_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='last_name',
        ),
    ]
