# Generated by Django 4.2.13 on 2024-06-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacSearch', '0007_remove_resume_first_name_remove_resume_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
