# Generated by Django 4.2.13 on 2024-06-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacSearch', '0012_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteVacancies',
        ),
    ]
