# Generated by Django 4.2.13 on 2024-06-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacSearch', '0014_favoritevacancies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteVacancies',
        ),
    ]
